basePath: /api/v1
definitions:
  models.Actor:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.Genre:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.Movie:
    properties:
      actors:
        items:
          $ref: '#/definitions/models.Actor'
        type: array
      created_at:
        type: string
      genre:
        $ref: '#/definitions/models.Genre'
      genre_id:
        description: nullable
        type: integer
      id:
        type: integer
      release_year:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample movies API with Fiber and Swagger.
  title: Movies API
  version: "1.0"
paths:
  /movies:
    get:
      consumes:
      - application/json
      description: Get details of all movies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Movie'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all movies
      tags:
      - movies
swagger: "2.0"
